### ISSUE TITLE
Beginner-Friendly Articles #2

### ISSUE THREAD

**Issue by mahmudurmahid** [mahmudurmahid/individual-formative-assessment#2]
**User Story:** 
As a former professional athlete, I want to read beginner-friendly articles on mental health so that I can understand common issues and how to manage them.

**Acceptance Criteria**

- [x] An “About” page displays beginner-friendly mental health articles.
- [x] Each article preview is displayed in a card format with a “FInd Out More” button.

**Tasks**

- [x] Design an “About” page with Bootstrap cards, each summarizing an article.
- [x] Implement “Read more” buttons on article previews to expand into full articles or link to dedicated pages.
