### ISSUE TITLE
Mobile Accessibility #4

### ISSUE THREAD

**Issue by mahmudurmahid** [mahmudurmahid/individual-formative-assessment#4]
**User Story:** 
As a former professional athlete, I want the website to be accessible on my mobile device so that I can access information on the go.

**Acceptance Criteria**

- [ ] All website pages are fully responsive across desktop and mobile devices.

**Tasks**

- [ ] Use Bootstrap’s grid system to ensure responsive layouts across all pages.
- [ ] Test each page on various mobile devices.
