### ISSUE TITLE
Quotes for Motivation #8

### ISSUE THREAD

**Issue by mahmudurmahid** [mahmudurmahid/individual-formative-assessment#6]
**User Story:** 
As a former professional athlete, I want to read success stories from other athletes so that I can feel motivated and supported.

**Acceptance Criteria**

- [ ] There are athlete-related quotes about mental health.
- [ ] A pagination or carousel feature allows users to view multiple stories.

**Tasks**

- [ ] Develop a carousel using Bootstrap for quotes.
- [ ] Implement pagination or a carousel for displaying multiple testimonials.
